src/eval.cpp

Rook and queen evaluations.
They are the same as knight, except rook only evaluates files.

Evaluation

---

src/bitboard.cpp
src/bitboard.hpp
src/search.cpp
src/search.hpp
src/uci.cpp

Non-recursive depth first search algorithm.
NPS = 50000
Most of the later optimization can be done in `movegen` and `eval`.

Search Algorithm

---

src/bitboard.cpp
src/uci.cpp

Made variables constant and reference.
NPS on branch `main`: 451668.5437
NPS on branch `movegen`: 720094.2551

Move Generation Optimizations

---

src/uci.cpp
tests/movegen_perft.py

Now, the command for triggering perft is `go perft 4`.
The engine also prints out nodes for each move, and the final nodes, nps, and time.
Also changed commands in `tests/movegen_perft.py`.
Tested and got same results.

Perft Improvements

---

src/eval.cpp
src/eval.hpp

Changed the way `pawn_structure` works.

Pawn eval.

---

src/eval.cpp

A clear and concise description of changes made.
Information such as testing, bugs, etc.

Change doubled to stacked

---

src/bitboard.hpp

Changed vectors to arrays:
```
// old
const vector<vector<char>> DIR_R = ...;
// new
const char DIR_R[4][2] = ...;
```
NPS increased from 1130k to 1140k.

Array Move Generation

---

src/perft.cpp
src/perft.hpp
src/uci.cpp

Push perft: `pushperft 1000`
Around 2.2 million nps.

Push Performance Test.

---

src/eval.cpp
src/eval.hpp
src/options.cpp
src/options.hpp
src/uci.cpp

Knight evaluation.
Looks at the distance to the center.
Tested and works.

Eval Knight

---

src/endgame.cpp
src/endgame.hpp
src/search.cpp
src/uci.cpp

Endgame algorithm structure and queen mate algorithm.
Tested and works.

Queen Mate

---

src/options.cpp
src/options.hpp
src/search.cpp
src/search.hpp
src/uci.cpp

Minor bug fixes:
* Fixed UCI output bugs.
* Removed stop early. Look at commit for more info.
* Improved time management algorithm.
Bench: 766294

Patrick Patch 1

---

src/eval.cpp
src/options.cpp
src/options.hpp
src/search.cpp
src/uci.cpp

Bug fixes and small eval optimizations.
Same results as main.

Patrick Patch 2

---

src/uci.cpp

Optimize `src/uci.cpp`. Added consts.
No testing required.

Arjun patch 1

---

README.md
docs/compiling.md
src/bitboard.cpp
src/bitboard.hpp
src/debug.hpp

Optimizations, formatting, spelling fixes
Also a debug mode. Edit file `src/debug.hpp` to toggle debug on/off.
Same results as `main` for depth 6 search.

Patrick Patch 3

---

src/bitboard.cpp
src/eval.cpp
src/perft.cpp
src/uci.cpp
tests/randpos.py

Formatting and small optimizations.
Same output as depth 6 search.

Arjun patch 2

---

src/bitboard.cpp
src/endgame.cpp

Locations optimizations
Benchmark results:
Nodes: 765689

Movegen optimizations.

---

src/endgame.cpp

Added bug fixes, optimizations, formatting.
Bench: 1516

Arjun Patch 4

---

src/bitboard.cpp
src/eval.cpp
src/hash.cpp
src/options.cpp
src/search.cpp
src/search.hpp
src/uci.cpp
src/utils.cpp
src/utils.hpp

Optimizations, formatting.
Bench: 765689

Arjun patch 5

---

CMakeLists.txt
src/bitboard.cpp
src/bitboard.hpp
src/endgame.cpp
src/eval.cpp
src/hash.cpp
src/main.cpp
src/options.cpp
src/search.cpp
src/uci.cpp
src/utils.cpp

Added `-Wall` flag to `g++`. Shows all warnings.
Resolved all warnings generated from `-Wall`.
Same bench as `main` (766265)

Compiler Warnings

---

src/eval.cpp

Commented pawn structure and pawn attack evaluation.
Estimate 20-50 ELO stronger than `search`.

Eval Optimization
